### PR TITLE
Fallback to finding the page using the reference

### LINKED ISSUE #722: Unable to flatten PDF if widget doesn't have P reference
When running `form.flatten()` on some PDFs, like from this [this](https://pdf-lib.js.org/#create-form) example, I get this error:
```
 Error: Failed to find page undefined for element favorite.superhero
    at _loop_1 (/node_modules/pdf-lib/cjs/api/form/PDFForm.js:463:27)
    at PDFForm.flatten (/node_modules/pdf-lib/cjs/api/form/PDFForm.js:492:17)
```

Here is an [example](https://github.com/Hopding/pdf-lib/files/5741532/form_on_3rd.pdf) of PDF that will produce this error and where form isn't on 1st page. (Originally posted [here](https://github.com/Hopding/pdf-lib/pull/716#issuecomment-751115024))

### PR DESCRIPTION
**Pull request by btecu**
Fixes #722.

### CODE REVIEW

**Comment by Hopding** [comment]
Please see https://github.com/Hopding/pdf-lib/issues/722#issuecomment-753511561.

**Comment by btecu** [comment]
Bonus: I've added `form.removeField()` since it seems to be a feature other people have been asking for.

File: src/api/PDFDocument.ts [hunk 1]
```diff
@@ -1264,6 +1265,20 @@ export default class PDFDocument {
     return dataUri ? `data:application/pdf;base64,${base64}` : base64;
   }
 
+  findPageForRef(ref: PDFRef): PDFPage {
```
Comment (Hopding) [inline src/api/PDFDocument.ts:1268]: Can we rename this so that it's clear the ref should be that of an annotation?
```suggestion
  findPageForAnnotationRef(ref: PDFRef): PDFPage {
```

File: src/api/PDFDocument.ts [hunk 2]
```diff
@@ -1264,6 +1265,20 @@ export default class PDFDocument {
...
+    for (let idx = 0, len = pages.length; idx < len; idx++) {
+      const page = pages[idx];
+      const annotations = page.node.Annots();
+
+      if (annotations?.indexOf(ref) !== undefined) {
+        return page;
+      }
+    }
+
+    throw new Error(`Could not find page for PDFRef ${ref}`);
```
Comment (Hopding) [inline src/api/PDFDocument.ts:1279]: I'd like to avoid throwing an error here in order to keep this method as flexible as possible. It may be used in scenarios where the caller isn't sure whether a ref lookup will succeed or not.
```suggestion
    return undefined;
```

File: src/api/form/PDFForm.ts [hunk 3]
```diff
@@ -591,11 +590,25 @@ export default class PDFForm {
         page.pushOperators(...operators);
       }
 
-      this.acroForm.removeField(field.ref);
-      this.doc.context.delete(field.ref);
+      this.removeField(field);
```
Comment (Hopding) [inline src/api/form/PDFForm.ts:593]: I wonder if we should also remove the widgets themselves from their page's `Annots` array after flattening them? They don't seem to impact how readers render the document, but they are dead weight. Not strictly necessary though.

File: src/core/PDFContext.ts [hunk 4]
```diff
@@ -163,6 +163,16 @@ class PDFContext {
     throw new UnexpectedObjectTypeError(types, result);
   }
 
+  getObjectRef(pdfObject: PDFObject): PDFRef {
+    for (const [ref, object] of this.indirectObjects.entries()) {
+      if (object === pdfObject) {
+        return ref;
+      }
+    }
```
Comment (Hopding) [inline src/core/PDFContext.ts:171]: I try to avoid changing the compiler config unless it's strictly necessary. Doing so can cause unexpected issues for library users. If we use `Array.from` we can implement this logic without changing the config.
```suggestion
    const entries = Array.from(this.indirectObjects.entries());
    for (let idx = 0, len = entries.length; idx < len; idx++) {
      const [ref, object] = entries[idx];
      if (object === pdfObject) {
        return ref;
      }
    }
```

File: src/core/PDFContext.ts [hunk 5]
```diff
@@ -163,6 +163,16 @@ class PDFContext {
...
+
+    throw new Error('Could not find PDFRef for PDFObject');
```
Comment (Hopding) [inline src/core/PDFContext.ts:173]: This method seems likely to be used in cases where the `PDFObject` isn't yet registered in the context.
```suggestion
    return undefined;
```

File: tsconfig.json [hunk 6]
```diff
@@ -15,7 +15,7 @@
     "tsBuildInfoFile": "./tsBuildInfo.json",
     "removeComments": false,
     "importHelpers": true,
-    "downlevelIteration": false,
+    "downlevelIteration": true,
```
Comment (Hopding) [inline tsconfig.json:18]: Should be able to avoid this config change per my previous suggestion.
```suggestion
    "downlevelIteration": false,
```

**Review by Hopding — CHANGES_REQUESTED** [review]
Looks great overall! Thanks @btecu. 

Request a few (hopefully small) changes. Then this will be ready to go 👍

**Comment by btecu** [comment]
@Hopding feedback addressed.

**Review by Hopding — APPROVED** [review]
Much appreciated. Thanks @btecu! I'm going to update the integration tests to cover all this logic and check some new scenarios for form flattening. Then I'll merge all this to `master`.
