### PR TITLE
Fix for #483 - Semi-transparent PNG rendered opaque in PDF

### LINKED ISSUE #483: Semi-transparent PNG rendered opaque in PDF
Im trying to watermark a PDF with a semi-transparent PNG, but the semi-transparent portions are being rendered fully opaque in resulting PDF.

I can't find anything in the docs regarding transparency... any help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by soadzoor**
Fixes #483 and #473

### CODE REVIEW

File: src/utils/png.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export class PNG {
 
     this.rgbChannel = rgbChannel;
 
-    const hasAlphaValues = alphaChannel.some((a) => a < 1);
+    const hasAlphaValues = alphaChannel.some((a) => a < 255);
```
Comment (Hopding) [inline src/utils/png.ts:61]: Thanks for tracking this down and fixing it!!! Much appreciated. Would you mind adding a quick unit test to prevent regressions? This will require a new test file: `tests/utils/png.spec.ts`.

Comment (soadzoor) [reply src/utils/png.ts:61]: @Hopding done! Let me know if it's okay (it's been a while since I wrote unit tests). That long line of Uin8Array might not be okay, but I'm not sure how to format that. It's ugly either way.. 😆 

The test itself passes with this PR (a < 255), and it fails without it (a < 1), so it's doing its job.

Comment (Hopding) [reply src/utils/png.ts:61]: Thanks @soadzoor. Just looked over it briefly and it looks good. I’ll try to get it merged this evening and released as soon as possible.
